apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kustomize-app
spec:
  selector:
    matchLabels:
      app: my-kustomize-app
  replicas: 2
  template:
    metadata:
      labels:
        app: my-kustomize-app
    spec:
      containers:
      - name: my-kustomize-app
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
